name: 04-Project-Practice-Workflow
on: [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
      - name: Lint
        run: |
          echo "Linting..."
          npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
      - name: Test
        run: |
          echo "Testing..."
          npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
      - name: Build
        run: |
          echo "Building..."
          npm run build
          echo "Build completed successfully!"
