name: 04-Project-Practice-Workflow
on: 
  pull_request:
    branches:
      - main
    types: opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
      - name: Lint
        run: |
          echo "Linting..."
          npm run lint
          echo "Lint completed successfully!"
      - name: Test
        run: |
          echo "Testing..."
          npm run test
          echo "Test completed successfully!"
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
      - name: Build
        run: |
          echo "Building..."
          npm run build
          echo "Build completed successfully!"
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: dist-files
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: dist-files
      - name: Output artifact
        run: |
          echo "Updating registries..."
          sudo apt update
          sudo apt install tree -y
          tree
          echo "Deploy completed successfully!"
