name: 04-Project-Practice-Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
          echo "Dependencies installed successfully!"
      - name: Lint
        run: |
          echo "Linting..."
          npm run lint
          echo "Lint completed successfully!"
      - name: Test
        run: |
          echo "Testing..."
          npm run test
          echo "Test completed successfully!"
  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      script-file: ${{ steps.publish-js-filename.outputs.script-file}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Nodejs Setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.19.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          npm audit fix
          echo "Dependencies installed successfully!"
      - name: Build
        run: |
          echo "Building..."
          npm run build
          echo "Build completed successfully!"
      - name: Publish JS Filename
        id: publish-js-filename
        run: |
          echo "Publishing JS filename..."
          find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT \;
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: dist-files
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: dist-files
      - name: Output artifact
        run: |
          echo "Running tree command..."
          tree
          echo "tree command completed successfully!"
          echo "Outputting script file..."
          echo ${{ needs.build.outputs.script-file}}
          echo "Script file output completed successfully!"
          echo "Deploy completed successfully!"
